# Generated by Django 3.1.2 on 2020-10-27 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylibr', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Style',
            new_name='Genre',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='style',
            new_name='genre',
        ),
    ]
