# Generated by Django 3.1.2 on 2020-10-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibr', '0003_auto_20201027_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(null=True, related_name='book', to='mylibr.Author'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(null=True, related_name='style', to='mylibr.Genre'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='year',
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.ManyToManyField(null=True, related_name='year', to='mylibr.Year'),
        ),
    ]
