# Generated by Django 3.1.2 on 2020-10-29 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylibr', '0005_auto_20201028_0703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Author',
            new_name='Authors',
        ),
        migrations.RenameModel(
            old_name='Genre',
            new_name='Genres',
        ),
        migrations.RenameModel(
            old_name='Year',
            new_name='Years',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AddField(
            model_name='library',
            name='author',
            field=models.ManyToManyField(related_name='library', to='mylibr.Authors'),
        ),
        migrations.AddField(
            model_name='library',
            name='book',
            field=models.ManyToManyField(related_name='library', to='mylibr.Books'),
        ),
        migrations.AddField(
            model_name='library',
            name='genre',
            field=models.ManyToManyField(related_name='library', to='mylibr.Genres'),
        ),
        migrations.AddField(
            model_name='library',
            name='year',
            field=models.ManyToManyField(related_name='library', to='mylibr.Years'),
        ),
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='mylibr.authors'),
        ),
        migrations.AddField(
            model_name='books',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='mylibr.genres'),
        ),
        migrations.AddField(
            model_name='books',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='mylibr.years'),
        ),
    ]
