# Generated by Django 3.1.2 on 2020-10-29 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylibr', '0006_auto_20201029_0645'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Library',
        ),
    ]
