# Generated by Django 3.1.2 on 2020-10-29 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylibr', '0007_delete_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genres', to='mylibr.genres'),
        ),
        migrations.AlterField(
            model_name='books',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='years', to='mylibr.years'),
        ),
    ]
