# Generated by Django 3.1.2 on 2020-10-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibr', '0008_auto_20201029_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('author', models.ManyToManyField(related_name='library', to='mylibr.Authors')),
                ('genre', models.ManyToManyField(related_name='library', to='mylibr.Genres')),
                ('year', models.ManyToManyField(related_name='library', to='mylibr.Years')),
            ],
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
