# Generated by Django 3.1.2 on 2020-10-30 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylibr', '0011_auto_20201030_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='book',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='mylibr.authors'),
        ),
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genre', to='mylibr.genres'),
        ),
        migrations.AlterField(
            model_name='books',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='year', to='mylibr.years'),
        ),
    ]
