# Generated by Django 3.1.2 on 2020-11-02 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylibr', '0015_auto_20201030_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='mylibr.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genre', to='mylibr.genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='year', to='mylibr.year'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='year',
            name='name',
            field=models.IntegerField(blank=True),
        ),
    ]
