# Generated by Django 3.1.2 on 2020-11-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibr', '0020_auto_20201105_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
